#!/usr/bin/env bash

# logfiles

section_01_dir="${home_directory}/results/01"
section_02_dir="${home_directory}/results/02"
section_03_dir="${home_directory}/results/03"
section_04_dir="${home_directory}/results/04"
section_05_dir="${home_directory}/results/05"

section_01_logfile="${section_01_dir}/logs/log.txt"
section_02_logfile="${section_02_dir}/logs/log.txt"
section_03_logfile="${section_03_dir}/logs/log.txt"
section_04_logfile="${section_04_dir}/logs/log.txt"
section_05_logfile="${section_05_dir}/logs/log.txt"

#Check data
controlsnps_file="${home_directory}/resources/genetics/example-snp-check.txt"
snplist="${home_directory}/resources/genetics/snplist.txt"

# phenotypes present in the dataset
phenotype_list="${section_01_dir}/phenotype_list.txt"

#plink path
plink="${home_directory}/resources/./plink1.90"


