#!/usr/bin/env bash

# logfiles

section_01_dir="${home_directory}/results/01"
section_01_logfile="${section_01_dir}/logs/log.txt"

phenotype_list="${section_01_dir}/phenotype_list.txt"

control_snps="${home_directory}/resources/genetics/snpsforbuildandposcheck.txt"
